baseURL: "https://sprkweb.github.io/"
defaultContentLanguage: en
staticDir:
  - static
  - node_modules/@fortawesome/fontawesome-free
sectionPagesMenu: main
taxonomies:
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: true
languages:
  ru:
    title: Вадим Сапрыкин
    description: "Сайт веб-разработчика Вадима Сапрыкина"
  en:
    title: Vadim Saprykin
    description: "Site of a web developer Vadim Saprykin"