baseURL: "https://sprkweb.github.io/"
defaultContentLanguage: ru
staticDir:
  - static
  - node_modules/@fortawesome/fontawesome-free
taxonomies:
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: true
languages:
  ru:
    title: Вадим Сапрыкин
    description: "Сайт веб-разработчика Вадима Сапрыкина"
  en:
    title: Vadim Saprykin
    description: "Site of a web developer Vadim Saprykin"
params:
  githubLink: "https://github.com/sprkweb/sprkweb.github.io"
  contacts:
    - title: Telegram
      text: "@saqew"
      link: "https://t.me/saqew"
      class: "fab fa-telegram"

    - title: Email
      text: "sprkweb@ya.ru"
      link: "mailto:sprkweb@ya.ru"
      class: "fas fa-envelope"

    - title: GitHub
      text: "sprkweb"
      link: "https://github.com/sprkweb"
      class: "fab fa-github"
menu:
  - main
imaging:
  quality: 85 # процентов
  hint: picture
  resampleFilter: Lanczos
enableGitInfo: true
