baseURL: "https://sprkweb.github.io/"
defaultContentLanguage: en
languages:
  ru:
    title: Вадим Сапрыкин
  en:
    title: Vadim Saprykin
staticDir:
  - static
  - node_modules/@fortawesome/fontawesome-free
markup:
  goldmark:
    renderer:
      unsafe: true