baseURL: "https://www.sprkweb.dev/"
defaultContentLanguage: ru
staticDir:
  - static
sectionPagesMenu: main
taxonomies:
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    ordered: true
languages:
  ru:
    title: Вадим Сапрыкин
    description: "Вадим Сапрыкин - бэкенд Golang разработчик, заинтересованный в изучении почти всего, пишет свои мысли о разных технологиях, идеях и своих проектах."
  en:
    title: Vadim Saprykin
    description: "Vadim Saprykin is a backend Golang developer interested in almost anything."
params:
  githubLink: "https://github.com/sprkweb/sprkweb.github.io"
  contacts:
    - title: Telegram
      text: "@saqew"
      link: "https://t.me/saqew"
      icon: "telegram"

    - title: Email
      text: "sprkweb@ya.ru"
      link: "mailto:sprkweb@ya.ru"
      icon: "mail"

    - title: GitHub
      text: "sprkweb"
      link: "https://github.com/sprkweb"
      icon: "github"

    - title: LinkedIn
      text: "sprkweb"
      link: "https://www.linkedin.com/in/sprkweb/"
      icon: "linkedin"
menu:
  - main
imaging:
  quality: 85 # процентов
  hint: picture
  resampleFilter: Lanczos
enableGitInfo: true
