baseURL: "https://www.sprkweb.dev/"
defaultContentLanguage: ru
staticDir:
  - static
  - node_modules/@fortawesome/fontawesome-free
taxonomies:
  tag: tags
markup:
  goldmark:
    renderer:
      unsafe: true
languages:
  ru:
    title: Вадим Сапрыкин
    description: "Вадим Сапрыкин - веб-разработчик, заинтересованный в изучении почти всего, пишет свои мысли о разных технологиях, идеях и своих проектах."
  en:
    title: Vadim Saprykin
    description: "Vadim Saprykin is a web developer interested in almost anything."
params:
  githubLink: "https://github.com/sprkweb/sprkweb.github.io"
  contacts:
    - title: Telegram
      text: "@saqew"
      link: "https://t.me/saqew"
      iconClass: "fab fa-telegram"

    - title: Email
      text: "sprkweb@ya.ru"
      link: "mailto:sprkweb@ya.ru"
      iconClass: "fas fa-envelope"

    - title: GitHub
      text: "sprkweb"
      link: "https://github.com/sprkweb"
      iconClass: "fab fa-github"

    - title: LinkedIn
      text: "sprkweb"
      link: "https://www.linkedin.com/in/sprkweb/"
      iconClass: "fab fa-linkedin-in"
menu:
  - main
imaging:
  quality: 85 # процентов
  hint: picture
  resampleFilter: Lanczos
enableGitInfo: true
